name: Build
on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  linux-build:
    name: Build
    runs-on: ubuntu-24.04-arm
    strategy:
      fail-fast: false
      matrix:
        SYSCALL_RECORD: [0, 1]
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build/Test
        env:
          SYSCALL_RECORD: ${{ matrix.SYSCALL_RECORD }}
        run: |
          make clean
          make -C apps/basic clean
          make
          make -C apps/basic
          LIBSVCHOOK=./apps/basic/libsvchook_basic.so LD_PRELOAD=./libsvchook.so ls | grep "output from hook_function"
      - name: Format
        run: |
          make fmt
          make -C apps/basic fmt
          test -z "$(git status --porcelain)"
  freebsd-build:
    name: FreeBSD Build
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build on FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          arch: aarch64
          usesh: true
          prepare: |
            pkg install -y llvm
          run: |
            make clean
            make -C apps/basic clean
            make
            make -C apps/basic
            make fmt
            make -C apps/basic fmt
            test -z "$(git status --porcelain)"
  android-build:
    name: Android Cross Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        SYSCALL_RECORD: [0, 1]
    env:
      ANDROID_VERSION: 21
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Build
        env:
          CC: aarch64-linux-android${{ env.ANDROID_VERSION }}-clang
          SYSCALL_RECORD: ${{ matrix.SYSCALL_RECORD }}
        run: |
          export PATH=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          make clean
          make -C apps/basic clean
          make
          make -C apps/basic
      - name: Format
        run: |
          make fmt
          make -C apps/basic fmt
          test -z "$(git status --porcelain)"
